export const FETCH_RAND_POKEMON = 'FETCH_RAND_POKEMON';

export const TURN_SCREEN_ON = 'TURN_SCREEN_ON';

export const TURN_SCREEN_OFF = 'TURN_SCREEN_OFF';

export const FETCH_SPECIFIC_POKEMON = 'FETCH_SPECIFIC_POKEMON';

export const SAVE_CUR_POKEMON = 'SAVE_CUR_POKEMON';

export const SEARCH_POKEMON = 'SEARCH_POKEMON';
